name: Integration
on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, edited, reopened, synchronize, review_requested, assigned]
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Current Branch is $branch."
    outputs:
      branch: ${{ steps.check_branch.outputs.branch }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: npm install

      - name: Set Version
        id: version
        run: |
          packageVersion=$(npx -c 'echo "$npm_package_version"')
          shortSHA=$(git rev-parse --short ${{ github.sha }})
          echo "version=$packageVersion-$shortSHA" >> $GITHUB_OUTPUT

      - name: Build vsix
        run: npx vsce package ${{ steps.version.outputs.version }} --no-git-tag-version -o api-insights-vscode-${{ steps.version.outputs.version }}.vsix

      - uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"

  integration:
    if: needs.check.outputs.branch == 'main'
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:
      - uses: actions/download-artifact@v3

      - name: Check AWS CLI
        run: aws --version

      - name: Upload to AWS S3
        run: aws s3 sync ./artifact s3://${{ secrets.AWS_BUCKET }}/${{ secrets.AWS_FOLDER }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2